{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "service-account.name" . }}
  labels: {{- include "chart.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
  {{- if or .Values.annotations .Values.serviceAccount.annotations }}
  annotations:
    {{- if .Values.serviceAccount.annotations }}
    {{- tpl (.Values.serviceAccount.annotations | toYaml) $ | nindent 4 }}
    {{- end }}
    {{- if .Values.annotations }}
    {{- tpl (.Values.annotations | toYaml) $ | nindent 4 }}
    {{- end }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
