{{- if eq .Values.tarantool.failover.mode "stateful" }}
{{- if and (eq .Values.tarantool.failover.stateProvider "etcd2") (not (eq .Values.tarantool.failover.etcd2.password "")) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cartridge.resource.fullname" (dict "context" . "suffix" "etcd2") }}
  labels: {{- include "cartridge.labels" . | nindent 4 }}
  {{- if .Values.annotations }}
  annotations: {{- tpl (.Values.annotations | toYaml) $ | nindent 4 }}
  {{- end }}
data:
  etcd2-password: "{{ .Values.tarantool.failover.etcd2.password | b64enc }}"
{{- end -}}

{{- if and (eq .Values.tarantool.failover.stateProvider "stateboard") (not (eq .Values.tarantool.failover.etcd2.password "")) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cartridge.resource.fullname" (dict "context" . "suffix" "stateboard") }}
  labels: {{- include "cartridge.labels" . | nindent 4 }}
  {{- if .Values.annotations }}
  annotations: {{- tpl (.Values.annotations | toYaml) $ | nindent 4 }}
  {{- end }}
data:
  stateboard-password: "{{ .Values.tarantool.failover.stateboard.password | b64enc }}"
{{- end -}}
{{- end -}}
