name: Release Charts

on:
  workflow_run:
    workflows:
      - Lint and Test Charts
    branches:
      - master
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.10.0

    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        check-latest: true

    - name: Run chart-releaser
      uses: ntwklr/nexus-helm-chart-releaser-action@v0.0.5
      with:
        charts_repo_url: https://nexus.ops.tarantool.io/repository/helm/
        username: "${{ secrets.NEXUS_USERNAME }}"
        password: "${{ secrets.NEXUS_PASSWORD }}"
      env:
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"